.pipeline: &pipeline
  - docker:
      image: node:lts-alpine
      volumes:
        - /root/.npm:cow

    imports:
      - https://cnb.cool/liuuu/cases/secret/-/blob/main/env.yml

    stages:
      - name: build application
        script: |
          npm install -g pnpm --register=https://registry.npmmirror.com
          pnpm install
          pnpm run build

      # - name: upload application
      #   image: tencentcom/coscli
      #   commands: |
      #     coscli config set --secret_id $COS_SECRET_ID --secret_key $COS_SECRET_KEY
      #     coscli config add --init-skip=true -b $COS_BUCKET -r $COS_REGION
      #     coscli cp ./out cos://$COS_BUCKET -r

      - name: upload application
        image: tencentcom/scp
        settings:
          host: $REMOTE_HOST
          username: $REMOTE_USERNAME
          password: $REMOTE_PASSWORD
          target: /home/wwwroot/2501_fe
          source: ./out

main:
  pull_request:
    - <<: *pipeline
      env:
        COS_BUCKET: hk-1351840111
        COS_REGION: ap-hongkong
  push:
    - <<: *pipeline
      env:
        COS_BUCKET: hk-1351840111
        COS_REGION: ap-hongkong
  web_trigger_prod:
    - <<: *pipeline
      env:
        COS_BUCKET: hk-1351840111
        COS_REGION: ap-hongkong
